alias ll="ls -al"

alias jump="ssh -p 9527 xiaozhou.tu@jmp.nioint.com"

git config --global alias.br 'branch'

git config --global alias.co 'checkout'
git config --global alias.ad 'add .'
git config --global alias.cm 'commit -am'

git config --global alias.rs 'reset HEAD'
git config --global alias.rb 'checkout --'
git config --global alias.rollback 'checkout --'

git config --global alias.ps 'push origin'
git config --global alias.pl 'pull origin'

git config --global alias.df 'diff'
git config --global alias.st 'status'

git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

export MAVEN_HOME=/Users/xiaozhou.tu/Maven/apache-maven-3.8.5
export PATH=$PATH:$MAVEN_HOME/bin

export GRADLE_HOME=/Users/xiaozhou.tu/Gradle/gradle-7.6.1
export PATH=$PATH:$GRADLE_HOME/bin

export JAVA_HOME_8=/Library/Java/JavaVirtualMachines/jdk1.8.0_351.jdk/Contents/Home
export JAVA_HOME_11=/Library/Java/JavaVirtualMachines/jdk-11.0.17.jdk/Contents/Home
export JAVA_HOME_17=/Library/Java/JavaVirtualMachines/jdk-17.0.3.1.jdk/Contents/Home
export JAVA_HOME=$JAVA_HOME_17
export PATH=$PATH:$JAVA_HOME/bin


export PATH=$PATH:/usr/local/mysql/bin


alias jdk8="export JAVA_HOME=$JAVA_HOME_8"
alias jdk11="export JAVA_HOME=$JAVA_HOME_11"
alias jdk17="export JAVA_HOME=$JAVA_HOME_17"

export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"

___MY_VMOPTIONS_SHELL_FILE="${HOME}/.jetbrains.vmoptions.sh"; if [ -f "${___MY_VMOPTIONS_SHELL_FILE}" ]; then . "${___MY_VMOPTIONS_SHELL_FILE}"; fi
